  
name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: "foxy",
            ROS_REPO: "main",
            CATKIN_LINT: "true",
            OPT_VI: "-vi",
            CATKIN_LINT_ARGS: "--ignore unknown_package"}

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # install pigpio
      - run: wget https://github.com/joan2937/pigpio/archive/master.zip
      - run: unzip master.zip
      - run: cd pigpio-master
      - run: make
      - run: sudo make install
      - run: cd ..
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
